---
# Config options for map generation and world size, etc.

# Current world seed
seed: 1

# Frequency of the planet's continents. Higher frequency produces
# smaller, more numerous continents. This value is measured in radians.
continent_frequency: 1.0

# Lacunarity of the planet's continents. Changing this value produces
# slightly different continents. For the best results, this value should
# be random, but close to 2.0.
continent_lacunarity: 2.208984375

# Lacunarity of the planet's mountains. Changing the value produces
# slightly different mountains. For the best results, this value should
# be random, but close to 2.0.
mountain_lacunarity: 2.142578125

# Lacunarity of the planet's hills. Changing this value produces
# slightly different hills. For the best results, this value should be
# random, but close to 2.0.
hills_lacunarity: 2.162109375

# Lacunarity of the planet's plains. Changing this value produces
# slightly different plains. For the best results, this value should be
# random, but close to 2.0.
plains_lacunarity: 2.314453125

# Lacunarity of the planet's badlands. Changing this value produces
# slightly different badlands. For the best results, this value should
# be random, but close to 2.0.
badlands_lacunarity: 2.212890625

# Specifies the "twistiness" of the mountains.
mountains_twist: 1.0

# Specifies the "twistiness" of the hills.
hills_twist: 1.0

# Specifies the "twistiness" of the badlands.
badlands_twist: 1.0

# Specifies the planet's sea level. This value must be between -1.0
# (minimum planet elevation) and +1.0 (maximum planet elevation).
sea_level: 0.0

# Specifies the level on the planet in which continental shelves appear.
# This value must be between -1.0 (minimum planet elevation) and +1.0
# (maximum planet elevation), and must be less than `SEA_LEVEL`.
shelf_level: -0.375

# Determines the amount of mountainous terrain that appears on the
# planet. Values range from 0.0 (no mountains) to 1.0 (all terrain is
# covered in mountains). Mountains terrain will overlap hilly terrain.
# Because the badlands terrain may overlap parts of the mountainous
# terrain, setting `MOUNTAINS_AMOUNT` to 1.0 may not completely cover the
# terrain in mountains.
mountains_amount: 0.5

# Determines the amount of hilly terrain that appears on the planet.
# Values range from 0.0 (no hills) to 1.0 (all terrain is covered in
# hills). This value must be less than `MOUNTAINS_AMOUNT`. Because the
# mountains terrain will overlap parts of the hilly terrain, and the
# badlands terrain may overlap parts of the hilly terrain, setting
# `HILLS_AMOUNT` to 1.0 may not completely cover the terrain in hills.
hills_amount: 0.75

# Determines the amount of badlands terrain that covers the planet.
# Values range from 0.0 (no badlands) to 1.0 (all terrain is covered in
# badlands). Badlands terrain will overlap any other type of terrain.
badlands_amount: 0.3125

# Offset to apply to the terrain type definition. Low values (< 1.0)
# cause the rough areas to appear only at high elevations. High values
# (> 2.0) cause the rough areas to appear at any elevation. The
# percentage of rough areas on the planet are independent of this value.
terrain_offset: 1.0

# Specifies the amount of "glaciation" on the mountains. This value
# should be close to 1.0 and greater than 1.0.
mountain_glaciation: 1.375

# Scaling to apply to the base continent elevations, in planetary
# elevation units.
continent_height_scale: 0.25

# Maximum depth of the rivers, in planetary elevation units.
river_depth: 0.0234375

